sudo: required
services:
  - docker
   
before_install:
  - docker build -t stevensp123/docker-test -f ./client/Dockerfile.dev ./client
   
script:
  - docker run stevensp123/docker-test npm run test -- --coverage
    
after_success:
  - docker build -t stevensp123/multi-client ./client
  - docker build -t stevensp123/multi-nginx ./nginx
  - docker build -t stevensp123/multi-server ./server
  - docker build -t stevensp123/multi-worker ./worker
  
# Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID"  --password-stdin
  
# Take those images and push them to docker hub
  - docker push stevensp123/multi-client
  - docker push stevensp123/multi-nginx
  - docker push stevensp123/multi-server
  - docker push stevensp123/multi-worker
  
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-178380328131"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"