sudo: required
services:
  - docker
   
before_install:
  - docker build -t stevensp123/docker-test -f ./client/Dockerfile.dev ./client
   
script:
  - docker run stevensp123/docker-test npm run test -- --coverage
    
after_success:
  - docker build -t stevensp123/multi-client ./client
  - docker build -t stevensp123/multi-nginx ./nginx
  - docker build -t stevensp123/multi-server ./server
  - docker build -t stevensp123/multi-worker ./worker