sudo: required
services:
  - docker
   
before_install:
  - docker build -t stevensp123/docker-test -f ./client/Dockerfile.dev ./client
   
script:
  - docker run stevensp123/docker-test npm run test -- --coverage